all:
  hosts:
{%- for host in env["virtual-kubelet"] %}
    {{ hostvars[host].inventory_hostname }}:
      ip: {{ hostvars[host].ip }}
      access_ip: {{ hostvars[host].access_ip }}
      ansible_host: {{ hostvars[host].ansible_host }}
      ansible_ssh_user: {{ hostvars[host].ansible_ssh_user }}
      ansible_ssh_pass: "{{ hostvars[host].ansible_ssh_pass }}"
      ansible_become_pass: "{{ hostvars[host].ansible_become_pass }}"
{%- if "ansible_ssh_private_key_file" in hostvars[host] %}
      ansible_ssh_private_key_file: "{{ hostvars[host].ansible_ssh_private_key_file }}"
{%- endif %}
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
{%- endfor %}